external_error_count again

diff --git a/build/start b/build/start
--- a/build/start
+++ b/build/start
@@ -9,7 +9,7 @@ set -eE
 
 # Handle errors and debug
 ((LABRACKUP_DEBUG > 0)) && touch /frx/start.log
-((LABRACKUP_DEBUG > 1)) && set -x
+((LABRACKUP_DEBUG > 2)) && set -x
 function trap_err() {
     die "Fatal Error: /frx/start:$1$(((LABRACKUP_DEBUG > 0)) && echo && sed "$1q;d" /frx/start && echo && cat /frx/start.log)"
 }
@@ -138,34 +138,35 @@ function perform_backup() {
     echo_dated "Listing backuped files in '${local_path}':" 
     ls -AshR ${local_path} | trace_cmd
     if [[ -n "${external_path}" ]]; then
-        echo_dated "Uploading backuped files to external host..."
-        check_backup_conf_type ${backup} external_host string
-        check_backup_conf_type ${backup} external_user string
-        check_backup_conf_type ${backup} external_password string
-        check_backup_conf_type ${backup} external_path string
         local external_error=0
-        sshpass -p "${external_password}" sftp -P ${external_port} ${external_user}@${external_host} >> /frx/start.log 2>&1 <<< "$(sftp_mkdir ${external_path})" || external_error=1
-        if [[ "${external_error}" == 0 ]]; then
+        {
+            echo_dated "Uploading backuped files to external host..."
+            check_backup_conf_type ${backup} external_host string
+            check_backup_conf_type ${backup} external_user string
+            check_backup_conf_type ${backup} external_password string
+            check_backup_conf_type ${backup} external_path string
+            sshpass -p "${external_password}" sftp -P ${external_port} ${external_user}@${external_host} >> /frx/start.log 2>&1 <<< "$(sftp_mkdir ${external_path})"
             local external_files="$(sshpass -p "${external_password}" sftp -P ${external_port} ${external_user}@${external_host} 2>> /frx/start.log <<< "ls -l ${external_path}" | tail -n +2 | sed "s,${external_path}/,,g" | xargs -n 9 | cut -d' ' -f5,9)"
+            ((LABRACKUP_DEBUG > 1)) && echo -e "External files:\n${external_files}" | trace_cmd
             local local_files
             local local_filename
             mapfile -t local_files < <(ls -l ${local_path} | tail -n +2 | xargs -n 9 | cut -d' ' -f5,9)
             for local_file in "${local_files[@]}"; do
                 local_filename="$(echo "${local_file}" | cut -d' ' -f2)"
                 [[ -d "${local_path}/${local_filename}" ]] && local_file="${local_filename}"
+                ((LABRACKUP_DEBUG > 1)) && trace "Checking: '${local_file}' ($(echo "${external_files}" | grep "${local_file#* }"))"
                 if ! echo "${external_files}" | grep -q "${local_file}"; then
                     trace "Uploading '${local_filename}'... "
                     if [[ -n "${local_filename%/}" ]]; then
-                        sshpass -p "${external_password}" sftp -P ${external_port} ${external_user}@${external_host} >> /frx/start.log 2>&1 <<< "$(sftp_mkdir ${external_path}/${local_filename%/})"
+                        sshpass -p "${external_password}" sftp -P ${external_port} ${external_user}@${external_host} >> /frx/start.log 2>&1 <<< "$(sftp_mkdir ${external_path}/${local_filename%/})" || ((external_error++))
                     fi
-                    sshpass -p "${external_password}" sftp -P ${external_port} ${external_user}@${external_host}:${external_path} >> /frx/start.log 2>&1 <<< "put -r ${local_path}/${local_filename}"
+                    sshpass -p "${external_password}" sftp -P ${external_port} ${external_user}@${external_host}:${external_path} >> /frx/start.log 2>&1 <<< "put -r ${local_path}/${local_filename}" || ((external_error++))
                 fi
             done
             echo_dated "Disk space usage on external host:"
             sshpass -p "${external_password}" sftp -P ${external_port} ${external_user}@${external_host} 2>> /frx/start.log <<< "df -h ${external_path}" | tail -n +2 | trace_cmd
-        else
-            ((external_error_count++))
-        fi
+        } || ((external_error++))
+        ((external_error > 0)) && ((external_error_count++))
     fi
 }
 
@@ -210,6 +211,7 @@ done
 echo
 
 # Performing all backups
+set +e
 declare -A backup_path_size
 declare -i external_error_count=0
 info "Running backups... "
@@ -219,6 +221,7 @@ for backup in "${backup_list[@]}"; do
     perform_backup ${backup}
     echo
 done
+set -e
 
 # Display disk space usage for each backup filesystems
 declare -a local_path_list
